### ISSUE TITLE
Internal errors when decoding TokenizedStrings with tokenizedstring.get

### ISSUE THREAD

**Issue by ItsSven64** [TI-Toolkit/tivars_lib_py#20]
When using the following code:
![image](https://github.com/TI-Toolkit/tivars_lib_py/assets/98273148/f7da27ea-6ea0-409c-b73d-b06a22ff56ae)

I get the following output:
![image](https://github.com/TI-Toolkit/tivars_lib_py/assets/98273148/f94cec6b-bb6c-4ebc-9d66-5b0e88e94c11)

This is not helpful for the end user

An example here would be appreciated, as there is currently none, and the wiki is poorly documented.

**Comment by kg583** [comment]
The error is about as helpful as it can be because it says exactly what is wrong. It's attempting to concatenate `bytestream[index:][:1]`, a `tuple`, to `curr_bytes`, a `bytes` object. Indeed, you're calling `TokenizedString.get` on the return of `tokenizer.encode`, which is a tuple of a `bytes` object and an `OsVersion` as stated in [the docs](https://ti-toolkit.github.io/tivars_lib_py/tivars.tokenizer.html#encode) (which is notably _not_ the same as the wiki; the wiki is not intended to be library docs). You can see this error ahead of time from the output of `print(tokenized)`.

But, outside of that error chain, how exactly did you derive this workflow? `TokenizedString` is an almost purely internal type, and never touted as anything more than that. `.get` is similarly a interface for the Python descriptor protocol, _not_ a constructor. The type signature alone is often enough to guess what a method is doing; turning that last line into the functional `tivars.TokenizedString.get(tokenized[0])` would just give you back `"HELLO"`, which is certainly _not_ what you want.

Are you trying to construct a `TIProgram` or `TIString`? `examples/misc.py` includes relevant code for constructing these types, which is supposed to be dead easy:

```py
TIString("HELLO")
```

If you need to ensure tokenization for a particular model, [you can do that too](https://ti-toolkit.github.io/tivars_lib_py/tivars.types.tokenized.TIString.html#load_string):
```py
TIString.load_string("HELLO", model=TI_84PCET)
```
